### ISSUE TITLE
Scapy(?) Error on Launch

### ISSUE THREAD

**Issue by c0rndogs** [MisterBianco/BoopSuite#21]
When I fire up BoopSniff with standard arguments, it listens for a while and then gives me this (seemingly whenever it receives a packet):

```
Traceback (most recent call last):
  File "/usr/local/bin/BoopSniff", line 164, in <module>
    main()
  File "/usr/local/bin/BoopSniff", line 156, in main
    sniffer_object.run()
  File "/usr/share/modules/sniffer.py", line 329, in run
    store=0
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff
    r = prn(p)
  File "/usr/share/modules/sniffer.py", line 349, in sniff_packets
    self.handler_beacon(packet_object)
  File "/usr/share/modules/sniffer.py", line 420, in handler_beacon
    channel = packets.get_channel(packet)
  File "/usr/share/modules/packets.py", line 53, in get_channel
    dot11elt = packet.getlayer(Dot11Elt, ID=61)
TypeError: getlayer() got an unexpected keyword argument 'ID'
```
Running on a fresh install of Kali 2017.3 with an AWUS036ACH.

**Comment by MisterBianco** [comment]
This is due to not having the correct version of scapy. Scapy version needs to be the dev branch of scapy v2.3.3 I will have to work on including it during the install process.

**Comment by MisterBianco** [comment]
Okay try downloading latest version and run the install.py file again and let me know if it works

**Comment by c0rndogs** [comment]
Nice, seems to be working now.  Thanks!

**Comment by MisterBianco** [comment]
I will close this issue, thank you for submitting this!
