### ISSUE TITLE
BoopStrike Error

### ISSUE THREAD

**Issue by c0rndogs** [MisterBianco/BoopSuite#22]
When trying to run a generic BoopStrike, it looks like there is a relative path that causes the following error if your working directory is not BoopSuite/core.
```
Traceback (most recent call last):
  File "/usr/local/bin/BoopStrike", line 17, in <module>
    version_file = open("../VERSION", 'r')
IOError: [Errno 2] No such file or directory: '../VERSION'
```
If you navigate to the BoopSuite/core directory and run the same command, the following Scapy issue (opened a separate issue for this) happens:
```
Traceback (most recent call last):
  File "/usr/local/bin/BoopStrike", line 98, in <module>
    main()
  File "/usr/local/bin/BoopStrike", line 92, in main
    sniffer_object.run()
  File "/usr/share/modules/sniffer.py", line 329, in run
    store=0
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff
    r = prn(p)
  File "/usr/share/modules/sniffer.py", line 349, in sniff_packets
    self.handler_beacon(packet_object)
  File "/usr/share/modules/sniffer.py", line 420, in handler_beacon
    channel = packets.get_channel(packet)
  File "/usr/share/modules/packets.py", line 53, in get_channel
    dot11elt = packet.getlayer(Dot11Elt, ID=61)
TypeError: getlayer() got an unexpected keyword argument 'ID'
```

**Comment by MisterBianco** [comment]
Oh see and I didn't notice the local file issue, awesome I'll have it fixed and pushed in a few minutes

**Comment by MisterBianco** [comment]
Okay latest push should fix these issues, let me know if everything sails smoothly

**Comment by c0rndogs** [comment]
Looks like that just nuked the VERSION file, which causes the same error.

**Comment by MisterBianco** [comment]
Did you rerun the install.py file?

**Comment by c0rndogs** [comment]
Did not, just did a pull for the other issue and I'm letting it run now.  Will update in a few.

**Comment by c0rndogs** [comment]
This looks fixed to me.  Thanks again!
