### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by WindNinja** [MisterBianco/BoopSuite#28]
Are you still working on the project?

I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/BoopStrike", line 93, in <module>
    main()
  File "/usr/local/bin/BoopStrike", line 87, in main
    sniffer_object.run()
  File "/usr/share/modules/sniffer.py", line 338, in run
    store=0
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 944, in sniff
    r = prn(p)
  File "/usr/share/modules/sniffer.py", line 358, in sniff_packets
    self.handler_beacon(packet_object)
  File "/usr/share/modules/sniffer.py", line 439, in handler_beacon
    oui = packets.get_vendor(packet.addr3)
  File "/usr/share/modules/packets.py", line 123, in get_vendor
    return (EUI(addr3)).oui.registration().org
  File "/usr/lib/python2.7/dist-packages/netaddr/eui/__init__.py", line 478, in oui
    return OUI(self.value >> 24)
  File "/usr/lib/python2.7/dist-packages/netaddr/eui/__init__.py", line 98, in __init__
    self._parse_data(data, offset, size)
  File "/usr/lib/python2.7/dist-packages/netaddr/eui/__init__.py", line 145, in _parse_data
    record['org'] = line.split(None, 2)[2]
IndexError: list index out of range

I am not a specialist, but I think the update does not work properly. When I get the version number I see 2.0.0 and not 2.0.2. 

Hope to hear from you soon.

**Comment by MisterBianco** [comment]
This tool is getting a whole rewrite for an upcoming competition that I will be attending. It will include everything I have learned since creating this and I hope to bring alot of cool features. PyPI integration, logging, new scapy stuff etc.

I am sorry that boopsuite has fallen into disrepair, this will be rectified. School and other commitments are keeping me from spending more time on this :sob:
